spring.application.name=helloworld
# URL e Chave da API do football-data.org 
football.api.url=https://api.football-data.org/v4/competitions/WC/matches
football.api.key= f5644cfeca5140aabbc54cab254e2468